import os
import subprocess
import shutil
import logging

def compile_tex_to_pdf(input_path: str, output_dir: str = "output", engine: str = "pdflatex") -> str:
    """
    Compile a LaTeX file to PDF using the specified engine.
    
    Args:
        input_path: Path to the .tex file.
        output_dir: Directory where the PDF and intermediate files will be placed.
        engine: The LaTeX compiler to use (pdflatex, tectonic, xelatex, etc.).
        
    Returns:
        Path to the generated PDF.
    """
    if not os.path.exists(input_path):
        raise FileNotFoundError(f"LaTeX file not found at: {input_path}")

    os.makedirs(output_dir, exist_ok=True)
    
    # Check if the engine is available
    if not shutil.which(engine):
        raise RuntimeError(f"LaTeX engine '{engine}' not found. Please ensure it is installed and in your PATH.")

    filename = os.path.basename(input_path)
    jobname = os.path.splitext(filename)[0]
    
    print(f"  [LaTeX] Compiling {filename} using {engine}...")
    
    try:
        # Run the compiler
        # -interaction=nonstopmode prevents the compiler from waiting for user input on errors
        # -output-directory specifies where to put the output
        cmd = [
            engine,
            "-interaction=nonstopmode",
            f"-output-directory={output_dir}",
            input_path
        ]
        
        # Some engines like tectonic or latexmk manage multiple passes themselves.
        # But pdflatex often needs 2 passes for references/TOC.
        # For a resume/cover letter, 1 pass is usually enough, but we'll do 2 to be safe.
        for i in range(2):
            result = subprocess.run(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                check=True
            )
        
        pdf_path = os.path.join(output_dir, f"{jobname}.pdf")
        if os.path.exists(pdf_path):
            print(f"  [LaTeX] Successfully generated: {pdf_path}")
            _cleanup_aux_files(output_dir, jobname)
            return pdf_path
        else:
            raise RuntimeError(f"PDF was not generated at expected path: {pdf_path}")
            
    except subprocess.CalledProcessError as e:
        logging.error(f"LaTeX compilation failed:\nSTDOUT: {e.stdout}\nSTDERR: {e.stderr}")
        raise RuntimeError(f"LaTeX compilation failed for {filename}. Check logs for details.")

def _cleanup_aux_files(directory: str, jobname: str):
    """Remove auxiliary files generated by LaTeX (.aux, .log, .out, etc.)"""
    extensions = [".aux", ".log", ".out", ".toc", ".nav", ".snm", ".fls", ".fdb_latexmk"]
    for ext in extensions:
        aux_file = os.path.join(directory, f"{jobname}{ext}")
        if os.path.exists(aux_file):
            os.remove(aux_file)
