"""init_job_data

Revision ID: 3e38756db5c6
Revises: 
Create Date: 2026-03-27 11:26:33.610895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e38756db5c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_datas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('job_portal_type', sa.Enum('workday', 'upwork', 'linkedin', 'indeed', 'wellfound', 'other', name='jobportaltype'), nullable=True),
        sa.Column('job_url', sa.String(length=1024), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_datas_id'), 'job_datas', ['id'], unique=False)
    
    # Add dummy data
    from sqlalchemy.sql import table, column
    job_datas_table = table('job_datas',
        column('job_portal_type', sa.String),
        column('job_url', sa.String)
    )
    op.bulk_insert(job_datas_table, [
        {'job_portal_type': 'upwork', 'job_url': 'https://www.upwork.com/jobs/~0123456789abcdef'},
        {'job_portal_type': 'linkedin', 'job_url': 'https://www.linkedin.com/jobs/view/123456789/'},
        {'job_portal_type': 'indeed', 'job_url': 'https://www.indeed.com/viewjob?jk=1234567890abcdef'},
        {'job_portal_type': 'wellfound', 'job_url': 'https://wellfound.com/jobs/123456-software-engineer'}
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_datas_id'), table_name='job_datas')
    op.drop_table('job_datas')
    # ### end Alembic commands ###
