"""add_job_status

Revision ID: 8d1a83fc848d
Revises: 3e38756db5c6
Create Date: 2026-03-27 15:53:14.547376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1a83fc848d'
down_revision: Union[str, Sequence[str], None] = '3e38756db5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_datas', sa.Column('job_status', sa.Enum('active', 'applied', 'not_active', name='jobstatus'), nullable=True))
    
    # Populate existing rows with a default value
    op.execute("UPDATE job_datas SET job_status = 'active'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_datas', 'job_status')
    # ### end Alembic commands ###
